url: https://tomnissens.github.io
baseurl: 
#/agency-jekyll-theme/

# Site settings
title: Tom Nissens
email: tom.nissens@gmail.com
description: "Who's Dr. Tom Nissens?"


# Team names, titles and social links
people:
# - name: Kay Garland
  # pic: 1
  # position: Lead Designer
  # social:
    # - title: twitter
      # url: #
    # - title: facebook
      # url: #
    # - title: stack-overflow
      # url: #

- name: Dr. Tom Nissens
  pic: Tom
  position: Researcher | Data Scientist | Problem Solver
  social:
    - title: github
      url: https://github.com/TomNissens/
    - title: linkedin
      url: https://www.linkedin.com/in/tomnissens/
    - title: twitter
      url: https://twitter.com/TomNissens/

# - name: Diana Petersen
  # pic: 3
  # position: Lead Developer
  # social:
    # - title: twitter
      # url: #
    # - title: facebook
      # url: #
    # - title: google-plus
      # url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
   - title: github
     url: https://github.com/TomNissens/
   - title: linkedin
     url: https://www.linkedin.com/in/tomnissens/
   - title: twitter
     url: https://twitter.com/TomNissens/

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 

# Build settings
markdown: kramdown
permalink: pretty